export const validPaths = [
    {"urlPath":"getRandomGame", "resourcePath": "","contentType": "application", "extention": "json"},
    {"urlPath":"getAllGames", "resourcePath": "","contentType": "application", "extention": "json"},
    {"urlPath":"main", "resourcePath": "css/","contentType": "text", "extention": "css"},
    {"urlPath":"favicon-16x16", "resourcePath": "","contentType": "image", "extention": "png"},
    {"urlPath":"favicon-32x32", "resourcePath": "","contentType": "image", "extention": "png"},
    {"urlPath":"android-chrome-192x192", "resourcePath": "","contentType": "image", "extention": "png"},
    {"urlPath":"android-chrome-512x512", "resourcePath": "","contentType": "image", "extention": "png"},
    {"urlPath":"apple-touch-icon", "resourcePath": "","contentType": "image", "extention": "png"},
    {"urlPath":"site.webmanifest", "resourcePath": "","contentType": "application", "extention": "manifest+json"},
    {"urlPath":"Scouts_Logo_Marque_Purple", "resourcePath": "", "contentType": "image", "extention": "png"},
    {"urlPath":"randomGame", "resourcePath": "pages/", "contentType": "text", "extention": "html"},
    {"urlPath":"listOfGames","resourcePath": "pages/", "contentType": "text", "extention": "html"},
    {"urlPath":"homepage", "resourcePath": "pages/", "contentType": "text", "extention": "html"},
    {"urlPath":"listOfGames.js", "resourcePath": "js/", "contentType": "application", "extention": "javascript"},
    {"urlPath":"randomGames.js", "resourcePath": "js/", "contentType": "application;", "extention": "javascript"},
]